### ISSUE TITLE
Remove java.util.Date from model entities

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#205] opened 2023-08-20 17:15 UTC
As **a user**, I want to use [Java time API](https://josdem.io/techtalk/java/java_time_api/) instead of `java.util.Date` **so that** I can have the project using the latest features of Java

**Acceptance Criteria**
- I am not seeing `java.util.Date` in the project
- All test cases are passing

**Comment by sindhunaydu** [comment] 2023-08-20 23:28
hi @josdem, I would love to work on this enhancement, can you assign it to me?

**Comment by josdem** [comment] 2023-08-20 23:34
Hi @sindhunaydu I appreciate your collaboration; this issue is assigned to you. Happy to help if you have any questions.

**Comment by sindhunaydu** [comment] 2023-08-21 01:04
Hi @josdem, thanks for assigning this enhancement to me. I've started setting up the app locally and ran into couple of issues. I have some questions,
1. Do I need to setup MySQL locally to run the app? Do I also need it to run the tests? One recommendation related to this would be setup test configs (application-test.yml) which uses H2 DB instead of MySQL.
2. 13 tests are failing with the same error, could this be related to the MySQL setup, if so can you give me more info about setting it up (version etc)

`VetlogControllerTest > showing home page FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1804
            Caused by: org.hibernate.service.spi.ServiceException at AbstractServiceRegistryImpl.java:275
                Caused by: org.hibernate.HibernateException at DialectFactoryImpl.java:100`

**Comment by josdem** [comment] 2023-08-21 01:15
Hi @sindhunaydu Here are my answers:
1. Yes, we need to set up a MySQL database locally so that you can run the app or test cases; if you want to do it, run these scripts: https://github.com/josdem/vetlog-spring-boot/tree/master/src/main/resources/db/migration after creating the database. 
2. Seems like it is related to the database issue. Feel free to send the PR, and I can run the test cases for you.

Also, I like the idea of having `application-test.yml` feel free to create an issue so we can have it in our backlog.

**Comment by sindhunaydu** [comment] 2023-08-21 02:01
Got it, I installed MySQL and ran the scripts. Now I'm getting a different error :D 

**- starting the app**
`ERROR 84997 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'googleStorageWriter' defined in file [/.../vetlog-spring-boot/build/classes/java/main/com/jos/dem/vetlog/client/GoogleStorageWriter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googleCredentials' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/core/GcpContextAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.api.gax.core.CredentialsProvider]: Factory method 'googleCredentials' threw exception; nested exception is java.io.FileNotFoundException: class path resource [vetlog.json] cannot be opened because it does not exist
`
**- running tests**
`BreedControllerTest > getting dogs breeds FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:800
            Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:658
                Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
                    Caused by: java.io.FileNotFoundException at ClassPathResource.java:199
`
I've created a PR, can you run the tests? thanks!

**Comment by sindhunaydu** [comment] 2023-08-21 02:24
All the tests are passing and I was able to start the app locally.

**Comment by josdem** [comment] 2023-08-21 02:26
Awesome, I am glad it worked! Your collaboration is appreciated. 🙂

**Comment by sindhunaydu** [comment] 2023-08-21 02:29
Thanks for your help. Here's the PR - https://github.com/josdem/vetlog-spring-boot/pull/206/files

**Closed** 2023-08-23 11:16 UTC
Labels: enhancement, help wanted, in progress, development, good first issue
